"""
Example script: squared alpha values on a single triangle.

This file is a minimal, mathematically explicit sanity check for
:func:`homolipop.alpha.alpha_values_squared`.

Mathematical conventions
========================

Point cloud
-----------

Let

.. math::

   X = \\{x_0, x_1, x_2\\} \\subset \\mathbb R^2

be the point cloud given by the rows of the NumPy array ``points``.
Here

.. math::

   x_0 = (0,0),\\quad x_1 = (1,0),\\quad x_2 = (0,1).

Simplices
---------

We represent a simplex by a strictly increasing tuple of vertex indices.
Thus the single 2-simplex is

.. math::

   \\sigma = (0,1,2),

its edges are :math:`(0,1)`, :math:`(0,2)`, :math:`(1,2)`,
and its vertices are :math:`(0)`, :math:`(1)`, :math:`(2)`.

Squared alpha value
-------------------

For any simplex :math:`\\tau` with vertices :math:`V(\\tau) \\subset X`,
the squared alpha value is defined as

.. math::

   \\alpha^2(\\tau)
   =
   \\min_{c \\in \\mathbb R^2} \\max_{x \\in V(\\tau)} \\|x-c\\|^2
   \\in [0,\\infty).

Because :math:`V(\\tau)` is finite, the minimum exists.

In this example, the triangle :math:`\\sigma=(0,1,2)` is right-angled at :math:`x_0`.
Hence its smallest enclosing ball is the circle with diameter the hypotenuse
:math:`\\overline{x_1x_2}`. The center is the midpoint

.. math::

   c = \\tfrac12(x_1 + x_2) = \\left(\\tfrac12,\\tfrac12\\right),

and the squared radius is

.. math::

   \\alpha^2(\\sigma)
   = \\|x_1 - c\\|^2
   = \\left(\\tfrac12\\right)^2 + \\left(\\tfrac12\\right)^2
   = \\tfrac12.

Therefore the expected output is ``alpha.alpha_sq[(0, 1, 2)] == 0.5``
up to floating point arithmetic.

For edges :math:`(i,j)` one has

.. math::

   \\alpha^2(i,j) = \\tfrac14\\,\\|x_i - x_j\\|^2,

since the smallest enclosing ball of two points has diameter the segment between them.

For a vertex :math:`(i)` one has :math:`\\alpha^2(i)=0`.

Numerical contract
------------------

All values are computed as IEEE 64 bit floats. Exact equality is expected here
because the geometry uses dyadic rationals, but this is not guaranteed in general.
"""

from __future__ import annotations

import numpy as np

from homolipop.alpha import alpha_values_squared


def main() -> None:
    """
    Compute and print squared alpha values for a single Delaunay triangle.

    The script computes :math:`\\alpha^2` for all simplices of dimension at most 2
    generated by the triangle ``(0, 1, 2)`` and prints

    - the triangle value, compared against the known exact value :math:`1/2`
    - the edge values
    - the vertex values

    Notes
    -----
    This is a correctness sanity check for the basic geometric cases

    - a vertex has :math:`\\alpha^2 = 0`
    - an edge has :math:`\\alpha^2 = \\|x_i-x_j\\|^2 / 4`
    - a right triangle has :math:`\\alpha^2` equal to one quarter of the squared hypotenuse length
    """
    points = np.array(
        [
            [0.0, 0.0],
            [1.0, 0.0],
            [0.0, 1.0],
        ],
        dtype=float,
    )

    delaunay_triangles = [(0, 1, 2)]
    alpha = alpha_values_squared(points, delaunay_triangles, max_dim=2)

    expected_radius_sq = 0.5
    print("triangle alpha^2:", alpha.alpha_sq[(0, 1, 2)])
    print("expected:", expected_radius_sq)

    print("edges:")
    for e in [(0, 1), (0, 2), (1, 2)]:
        print(e, alpha.alpha_sq[e])

    print("vertices:")
    for v in [(0,), (1,), (2,)]:
        print(v, alpha.alpha_sq[v])


if __name__ == "__main__":
    main()