"""
Example script: persistent homology over :math:`\\mathbb F_5` on a single filtered triangle.

This file is identical in structure to the :math:`\\mathbb F_2` example, but uses the field
:math:`\\mathbb F_5` as coefficients.

For the specific filtered complex used here, the pairing produced by standard persistence
reduction does not depend on the choice of field, because the boundary coefficients are
only :math:`0` and :math:`\\pm 1`, and :math:`\\pm 1` are units in every field.

Mathematical conventions
========================

Filtered simplicial complex
---------------------------

Let :math:`K` be the abstract simplicial complex generated by the 2-simplex
:math:`(0,1,2)`. Let

.. math::

   \\sigma_0,\\sigma_1,\\dots,\\sigma_{m-1}

be the list ``simplices`` returned by :func:`homolipop.simplices.build_complex`.
This order is assumed to be a filtration order, meaning every face appears no later
than the simplex itself.

Define

.. math::

   K_i = \\langle \\sigma_0,\\dots,\\sigma_i \\rangle

to be the subcomplex generated by the first :math:`i+1` simplices in the list.

Coefficients
------------

Fix the prime :math:`p=5`. All homology groups are computed with coefficients in the field

.. math::

   \\mathbb F_5 = \\mathbb Z/5\\mathbb Z.

Persistent pairing format
-------------------------

The routine :func:`homolipop.persistence.persistent_homology_field` is assumed to return

- ``pairs`` as triples ``(birth, death, dim)``
- ``unpaired`` as pairs ``(birth, dim)``

with the meaning that a class in dimension ``dim`` is born when simplex ``birth`` enters
and dies when simplex ``death`` enters, or persists forever if unpaired.

Expected qualitative outcome
----------------------------

For a filled triangle, the persistence behaviour is as follows.

- One connected component in dimension 0 is born at the first vertex and remains unpaired.
- A 1-cycle is created when the last edge closing the triangle boundary appears and dies
  when the 2-simplex appears.

The exact integer indices depend on the simplex ordering returned by :func:`build_complex`.

Implementation contract
-----------------------

This script assumes that :func:`field_Fp(5)` constructs a coefficient field descriptor
for arithmetic in :math:`\\mathbb F_5`.
"""

from __future__ import annotations

from homolipop.persistence import field_Fp, persistent_homology_field
from homolipop.simplices import build_complex


def main() -> None:
    """
    Compute persistent homology over :math:`\\mathbb F_5` for a single filled triangle.

    The script prints

    - all paired events as ``(birth, death, dim)``
    - all unpaired events as ``(birth, dim)``
    """
    simplices = build_complex([(0, 1, 2)], max_dim=2).all_simplices
    result = persistent_homology_field(simplices, field=field_Fp(5))

    print("Pairs (birth, death, dim) over F5:")
    for pair in result.pairs:
        print(pair)

    print("Unpaired (birth, dim) over F5:")
    for u in result.unpaired:
        print(u)


if __name__ == "__main__":
    main()